### ISSUE TITLE
Feedback only - not an issue!

### ISSUE THREAD

**Issue by baqwas** [IBM/node-red-tensorflowjs#8]
Hello,

I tried the exercise on RPi2 & RPi3 but could not install the TensorFlow.js node _properly_. The message that I could not resolve is embedded in the output below:

`$ npm install /home/pi/projects/node-red-tensorflowjs/node-red-contrib-tfjs-object-detection
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> @tensorflow/tfjs-node@1.5.1 install /home/pi/projects/node-red-tensorflowjs/node-red-contrib-tfjs-object-detection/node_modules/@tensorflow/tfjs-node
> node scripts/install.js

CPU-linux-1.5.1.tar.gz
* Downloading libtensorflow
(node:3527) UnhandledPromiseRejectionWarning: Error: Unsupported system: cpu-linux-arm
    at getPlatformLibtensorflowUri (/home/pi/projects/node-red-tensorflowjs/node-red-contrib-tfjs-object-detection/node_modules/@tensorflow/tfjs-node/scripts/install.js:95:11)
    at downloadLibtensorflow (/home/pi/projects/node-red-tensorflowjs/node-red-contrib-tfjs-object-detection/node_modules/@tensorflow/tfjs-node/scripts/install.js:129:7)
(node:3527) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3527) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-red-contrib-tfjs-object-detection@0.0.1
added 90 packages from 95 contributors in 682.022s
$ `

I read the introductory statement about the testing being limited to RPi4 but since I have TF installed on the two platforms that I tried to emulate the exercise, I want to provide this feedback. Unless there is a workaround, please do not try to resolve the issue. It will be more expedient for me to obtain the correct platform - RPi4.

Kind regards.

**Comment by pvaneck** [comment]
Hey, thanks for bringing this up. Seems like there aren't currently any prebuilt libtensorflow binaries that correspond to the latest version of tfjs-node. I am pinning the version to 1.4.0 for now in #9. This version should stop the error your are encountering. Hopefully soon, we can get binaries for arm architectures readily available for the latest version.
